### ISSUE TITLE
Issue with an example

### ISSUE THREAD

**Issue by nsankar** [lucidrains/hourglass-transformer-pytorch#1]
@lucidrains  Just Awesome to see this super fast launch !

The third example under "For Images...." throws the following error .,

![image](https://user-images.githubusercontent.com/431890/141131569-4b820d9e-68df-410b-a967-c5b0d2f64118.png)

Then , when I gave the inputs with num_tokens = 20000,
    max_seq_len = 1024,  I got the following runtime error

![image](https://user-images.githubusercontent.com/431890/141132204-fe8c6467-3ce9-4dad-b292-3dddf8be88b4.png)

**Comment by lucidrains** [comment]
@nsankar oops, i fixed the readme :pray:
