### ISSUE TITLE
No option for rotary positional embeddings

### ISSUE THREAD

**Issue by vvvm23** [lucidrains/hourglass-transformer-pytorch#2]
For the ImageNet64 generation experiments, the original authors used rotary positional embeddings. I think it would be worth adding this feature to the repository.

I can prepare a pull request that solves this~

**Comment by lucidrains** [comment]
oh no way, can you point to me where in his code that he does this?

**Comment by lucidrains** [comment]
would be happy to add it as an option if so

**Comment by vvvm23** [comment]
I didn't actually look at their original implementation, I just saw this detail in the paper.

My Jax knowledge isn't great, but I think they probably did it by changing the attention wrapper used when initialising the transformer [here](https://github.com/google/trax/blob/d6cae2067dedd0490b78d831033607357e975015/trax/models/research/hourglass.py#L140) with something like [this](https://github.com/google/trax/blob/d6cae2067dedd0490b78d831033607357e975015/trax/layers/research/efficient_attention.py#L3494).

**Comment by vvvm23** [comment]
Relevant excerpt from paper:

> We replace relative attention in vanilla layers by LSH attention (...), which allows us to handle 12288-long sequences. To achieve relative attention parametrization, the LSH attention is combined with rotary positional embeddings (...). In shortened layers, standard relative attention is used. 

My pull request doesn't actually handle LSH attention though 🤔
